/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: App_Icon5                                             *
* Dimensions:  60 * 60                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmApp_Icon5;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsApp_Icon5[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalApp_Icon5 = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsApp_Icon5[0]
};

static GUI_CONST_STORAGE unsigned char _acApp_Icon5[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ____XXXX, XX______, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, _______X, X_______, __XXXXXX, XXX_____, _____XX_, ________, ________,
  ________, ______XX, XX______, _XXXXXXX, XXXXX___, ____XXXX, ________, ________,
  ________, _____XXX, XXX____X, XXXXXXXX, XXXXXXX_, ___XXXXX, X_______, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX, ________, ________,
  ________, _____XXX, XXXXXXXX, X_______, _____XXX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, ________, ______XX, XXXXXXXX, X_______, ________,
  ________, ____XXXX, XXXXXXX_, ________, _______X, XXXXXXXX, XX______, ________,
  ________, ___XXXXX, XXXXXX__, ________, _______X, XXXXXXXX, XXX_____, ________,
  _______X, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXXXXX_, ________,
  ______XX, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXXXXXX, ________,
  ______XX, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXXXXXX, ________,
  ______XX, XXXXXXXX, XXXXX___, ________, ________, XXXXXXXX, XXXXXXXX, ________,
  ______XX, XXXXXXXX, XXXXX___, ________, ________, XXXXXXXX, XXXXXXXX, ________,
  ______XX, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXXXXXX, ________,
  ______XX, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXXXX__, ________, ________, XXXXXXXX, XXXXXXX_, ________,
  ________, ____XXXX, XXXXXXX_, ________, _______X, XXXXXXXX, XX______, ________,
  ________, _____XXX, XXXXXXX_, ________, _______X, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, ________, ______XX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, X_______, _____XXX, XXXXXXXX, X_______, ________,
  ________, ______XX, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, _____XXX, XXX____X, XXXXXXXX, XXXXXX__, ___XXXXX, X_______, ________,
  ________, ______XX, XX______, __XXXXXX, XXXX____, ____XXXX, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ___XXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, ____XXXX, XX______, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmApp_Icon5 = {
  60, // xSize
  60, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acApp_Icon5,  // Pointer to picture data (indices)
  &_PalApp_Icon5   // Pointer to palette
};

/*************************** End of file ****************************/
