/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: App_Icon6                                             *
* Dimensions:  60 * 60                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmApp_Icon6;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsApp_Icon6[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalApp_Icon6 = {
  2,  // Number of entries
  1,  // Has transparency
  &_ColorsApp_Icon6[0]
};

static GUI_CONST_STORAGE unsigned char _acApp_Icon6[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, __XXXXX_, ________, _____XXX, XX______, ________, ________,
  ________, ________, XXXXXXXX, XX______, __XXXXXX, XXXX____, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ___XXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, __XXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XX______, ________,
  ________, __XXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XX______, ________,
  ________, _XXXXXX_, ______XX, XXXXXXXX, XXXXX___, XX__XXXX, XXX_____, ________,
  ________, _XXXXXX_, _______X, XXXXXXXX, XXXXX___, XXXXXXXX, XXX_____, ________,
  ________, _XXXXXX_, _______X, XXXXXXXX, XXXXX___, XXXX___X, XXX_____, ________,
  ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXX_____, ________,
  ________, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, __XX__XX, XXXX____, ________,
  ________, XXXXXXXX, XX__XXXX, XXX_____, XXXXXXX_, ___XXXXX, XXXX____, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, __XXXXXX, XXXX____, ________,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXXXX__, ________, ______XX, XXXXXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXXX___, ________, _______X, XXXXXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, _XXXXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXX_____, ________, ________, _XXXXXXX, XXXXX___, ________,
  ________, XXXXXXXX, XX______, ________, ________, __XXXXXX, XXXXX___, ________,
  ________, XXXXXXXX, X_______, ________, ________, ___XXXXX, XXXX____, ________,
  ________, _XXXXXXX, ________, ________, ________, _____XXX, XXXX____, ________,
  ________, __XXXX__, ________, ________, ________, ______XX, XX______, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmApp_Icon6 = {
  60, // xSize
  60, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acApp_Icon6,  // Pointer to picture data (indices)
  &_PalApp_Icon6   // Pointer to palette
};

/*************************** End of file ****************************/
